name: Build code

on: push

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Bundle
        run: yarn bundle
