name: Publish package to npm

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Bundle
        run: yarn bundle
      - name: Release
        run: yarn release
