name: Test code

on: push

jobs:
  test-code:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
